_BASE_: "../base-prox.yaml"
MODEL:
  NULL_CLASS: True
  NUM_HORIZON: 3
  DETECTION_LOSS:
    NAME: "ProposalProjectionIoUClassLoss"
    CLASSIFICATION_LAMBDA: 10.0
    # GIOU_LAMBDA: 2.0
    PROJECTION_LAMBDA: 1.0
    # USE_GIOU: True
    USE_FOCAL: True
  CLAMP_PREDS: True
  TRANSPORT_LOSS:
    TRANSPORT_LAMBDA: 1.0
  TRAIN_PROPOSAL_GENERATOR:
    NAME: "NoisedGroundTruth"
    GAUSSIAN_ERROR: 0.1
    USE_TIME: False
    NUM_PROPOSALS: 128
  NETWORK:
    POSITION_DIM: 4
    NAME: "ClassResidualNetV2"
    HIDDEN_SIZE: 64
  ENCODER:
    NAME: "LocalGlobalUnitedEncoder"
SOLVER:
  BACKBONE_MULTIPLIER: 0.1
  BASE_LR: 0.000025
  IMS_PER_BATCH: 12 # 16
  WANDB:
    ENABLED: False # True
    LOG_FREQUENCY: 500
  STEPS: (3000000, 3200000)
  MAX_ITER: 3600000
DATASETS:
  TRAIN: ("coco_2017_val_small",)
  TEST:  ("coco_2017_val_small",)
  AUGMENTATION:
    ENABLED: True
OUTPUT_DIR: "./output/better-noise"