_BASE_: "../base-prox.yaml"
MODEL:
  NUM_HORIZON: 5
  DETECTION_LOSS:
    NAME: "ClassificationBoxProposalProjectionLoss"
    CLASSIFICATION_LAMBDA: 3.0
    USE_FOCAL: True
  TRANSPORT_LOSS:
    TRANSPORT_LAMBDA: 1.0
  TRAIN_PROPOSAL_GENERATOR:
    NAME: "UniformRandomBoxes"
    NUM_PROPOSALS: 100
  NETWORK:
    POSITION_DIM: 4
    NAME: "ClassResidualNet"
  ENCODER:
    NAME: "LocalEncoder"
SOLVER:
  BASE_LR: 0.00001
  IMS_PER_BATCH: 1 # change thids
  WANDB:
    ENABLED: True
    LOG_FREQUENCY: 1000
DATASETS:
  TRAIN: ("coco_2017_train_1small",)
  TEST:  ("coco_2017_train_1small",)
  AUGMENTATION:
    ENABLED: True
OUTPUT_DIR: "./output/classification-local-test/lambda-3.0"