_BASE_: "../base-prox.yaml"
MODEL:
  NUM_HORIZON: 3
  DETECTION_LOSS:
    NAME: "ClassificationBoxProjectionLoss"
    CLASSIFICATION_LAMBDA: 0.1
  TRAIN_PROPOSAL_GENERATOR:
    NAME: "UniformRandomBoxes"
    NUM_PROPOSALS: 100
  NETWORK:
    POSITION_DIM: 4
    NAME: "ClassResidualNet"
SOLVER:
  # MAX_ITER: 100
  IMS_PER_BATCH: 12
  BASE_LR: 0.0001
  WANDB:
    ENABLED: True
    LOG_FREQUENCY: 500
TEST:
  EVAL_PERIOD: 5000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
  AUGMENTATION:
    ENABLED: True
OUTPUT_DIR: "./output/classification-test"
