_BASE_: "../base-prox.yaml"
SOLVER:
  MAX_ITER: 100
  IMS_PER_BATCH: 2
  WANDB:
    ENABLE: False

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)

OUTPUT_DIR: "./output/local-global-test-eval"

MODEL:
  ENCODER:
    NAME: LocalGlobalEncoder
  NUM_HORIZON: 2
  NETWORK:
    NAME: ClassResidualNet