_BASE_: "../base-prox.yaml"
MODEL:
  NUM_HORIZON: 5
  TRAIN_PROPOSAL_GENERATOR:
    NAME: "UniformRandomBoxes"
    NUM_PROPOSALS: 100
  ENCODER:
    NAME: "ResnetEncoder"
    POSITIONAL_EMBEDDINGS:
      TYPE: "sine"
SOLVER:
  IMS_PER_BATCH: 28
  WANDB:
    ENABLED: True
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
OUTPUT_DIR: "./output/resnet-sine-2"