_BASE_: "../base-prox.yaml"
MODEL:
  NUM_HORIZON: 5
  ENCODER:
    NAME: "ResnetEncoder"
    POSITIONAL_EMBEDDINGS:
      TYPE: "sine"
  NETWORK:
    NAME: "ClassResidualNet"
SOLVER:
  IMS_PER_BATCH: 9
  WANDB:
    ENABLED: True
    LOG_FREQUENCY: 20
DATASETS:
  TRAIN: ("synthetic_train_10",)
  TEST:  ("synthetic_val_10",)
  AUGMENTATION:
    ENABLED: False
OUTPUT_DIR: "./output/synthetic-class"