_BASE_: "../base-prox.yaml"
MODEL:
  NUM_HORIZON: 10
  DETECTION_LOSS:
    NAME: "BoxProjectionOriginLoss"
  TRAIN_PROPOSAL_GENERATOR:
    NAME: "NoisedGroundTruth"
    GAUSSIAN_ERROR: 0.1
    USE_TIME: True
    NUM_PROPOSALS: 100
  NETWORK:
    PE_DIM: 4
SOLVER:
  IMS_PER_BATCH: 9
  WANDB:
    ENABLED: True
    LOG_FREQUENCY: 20
DATASETS:
  TRAIN: ("synthetic_train_10",)
  TEST:  ("synthetic_val_10",)
  AUGMENTATION:
    ENABLED: False
OUTPUT_DIR: "./output/diffusion-test"