_BASE_: "../base-prox.yaml"
MODEL:
  NUM_HORIZON: 3
  DETECTION_LOSS:
    NAME: "ClassificationBoxProposalProjectionLoss"
    CLASSIFICATION_LAMBDA: 0.3
  TRAIN_PROPOSAL_GENERATOR:
    NAME: "UniformRandomBoxes"
    NUM_PROPOSALS: 100
  TRANSPORT_LOSS:
    BOX_DISTANCE_TYPE: "l2"
    TRANSPORT_LAMBDA: 4.0
  ENCODER:
    NAME: "LocalGlobalUnitedEncoder"
  NETWORK:
    NAME: "ClassResidualNetV2"
    POSITION_DIM: 4
    HIDDEN_SIZE: 64
  USE_NMS: True
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.00001
  WANDB:
    ENABLED: True
    LOG_FREQUENCY: 500
TEST:
  EVAL_PERIOD: 10000
DATASETS:
  TRAIN: ("coco_2017_val_small",)
  TEST: ("coco_2017_val_small",)
  AUGMENTATION:
    ENABLED: False
OUTPUT_DIR: "./output/small-v2"
DATALOADER:
  NUM_WORKERS: 4