from .box_distance_loss import BoxDistanceLoss
from .box_projection_loss import BoxProjectionLoss
from .box_projection_origin_loss import BoxProjectionOriginLoss
from .classification_box_projection_loss import ClassificationBoxProjectionLoss
from .classification_box_proposal_projection_loss import (
    ClassificationBoxProposalProjectionLoss,
)
from classification_loss import ClassificationLoss
