VERSION: 2
MODEL:
  META_ARCHITECTURE: "ProxModel"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    STRIDE_IN_1X1: False
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ROI_HEADS:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    POOLER_TYPE: "ROIAlignV2"
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 2
  TRAIN_PROPOSAL_GENERATOR:
    NAME: "UniformRandomBoxes"
    NUM_PROPOSALS: 100
    GAUSSIAN_ERROR: 0.001
    USE_TIME: False
    RATIO: 0.0
  INFERENCE_PROPOSAL_GENERATOR:
    NAME: "UniformRandomBoxes"
    NUM_PROPOSALS: 1024
  ENCODER:
    NAME: "LocalGlobalEncoder"
    DIMENSION: 256
    WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/torchvision/R-50.pkl"
    POSITIONAL_EMBEDDINGS:
      TYPE: "none"
      HIDDEN_DIM: 256
  NETWORK:
    NAME: "ResidualNet"
    INPUT_DIM: 4
    FEATURE_DIM: 256
    NUM_BLOCK: 3
    HIDDEN_SIZE: 128
    FEATURE_PROJ_DIM: 128
    INPUT_PROJ_DIM: 128
    POSITION_DIM: 4
  NUM_HORIZON: 8
  TRANSPORT_LOSS:
    NAME: "BoxDistanceLoss"
    BOX_DISTANCE_TYPE: "l2"
    TRANSPORT_LAMBDA: 1.0
  DETECTION_LOSS: 
    NAME: "BoxProjectionLoss"
    CLASSIFICATION_LAMBDA: 1.0
    USE_FOCAL: False
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    USE_GIOU: False
    GIOU_LAMBDA: 1.0
    PROJECTION_LAMBDA: 1.0
    IOU_THRESHOLD: 0.5
    NULL_CLASS_LAMBDA: 1.0
  CLASSIFICATION_LOSS:
    NAME: "ClassificationLoss"  
  USE_NMS: True
  CLAMP_PREDS: False  
  NULL_CLASS: False
  INFERENCE_LOG_PROBABILITY: 0.002 # 10 / 5000
SEED: 40244023
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00001
  BACKBONE_MULTIPLIER: 1.0
  CHECKPOINT_PERIOD: 3000
  STEPS: (350000, 420000)
  MAX_ITER: 450000
  AMP:
    ENABLED: True
  WANDB:
    ENABLED: False
    LOG_FREQUENCY: 100
  PROFILE: False
  OPTIMIZER: "AdamW"
  WEIGHT_DECAY: 0.0001
  WARMUP_ITERS: 1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
DATASETS:
  TRAIN_COUNT: 100
  AUGMENTATION:
    ENABLED: True
  TRAIN: ("synthetic_train_10",)
  TEST: ("synthetic_val_10",)
  NUM_CLASSES: 80
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
    FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 10000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
OUTPUT_DIR: "./output/base/"