_BASE_: "base-prox.yaml"
MODEL:
  ENCODER:
    NAME: "LocalGlobalEncoderPE"
  NUM_HORIZON: 4
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  CHECKPOINT_PERIOD: 1000

OUTPUT_DIR: "./output/local-global-pe"