_BASE_: "base-prox.yaml"
MODEL:
  NUM_HORIZON: 4
  TRAIN_PROPOSAL_GENERATOR:
    NAME: "UniformRandomBoxes"
    NUM_PROPOSALS: 100
  ENCODER:
    NAME: "LocalGlobalEncoderPE"
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  WANDB:
    ENABLED: True
INPUT:
  CROP:
    ENABLED: True
DATASETS:
 TRAIN: ("synthetic_train_10",)
 TEST:  ("synthetic_val_10",)
 AUGMENTATION:
  ENABLED: True

OUTPUT_DIR: "./output/local-global-pe-synthetic-debug"