_BASE_: "base-prox.yaml"
MODEL:
  ENCODER:
    NAME: "LocalGlobalEncoderPE"
  NUM_HORIZON: 5
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 1000

OUTPUT_DIR: "./output/local-global-pe"