_BASE_: "local-global_synthetic.yaml"
MODEL:
  NUM_HORIZON: 4
  TRAIN_PROPOSAL_GENERATOR:
    NAME: "UniformRandomBoxes"
    NUM_PROPOSALS: 100
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
INPUT:
  CROP:
    ENABLED: True
DATASETS:
  TRAIN: ("coco_2017_train_1000small",)
  TEST: ("coco_2017_val",)

OUTPUT_DIR: "./output/debug"