_BASE_: "base-prox.yaml"
MODEL:
  ENCODER:
    NAME: ResnetEncoder
  NUM_HORIZON: 5
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 1000
DATASETS:
  TRAIN: ("synthetic_train",)
  TEST:  ("synthetic_val",)

OUTPUT_DIR: "./output/resnet-debug"