_BASE_: "base-prox.yaml"
MODEL:
  ENCODER:
    NAME: LocalGlobalEncoder
  NUM_HORIZON: 7

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  CHECKPOINT_PERIOD: 1000
  WANDB:
    ENABLED: True

OUTPUT_DIR: "./output/zeric-1"
